name: fin_dall
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animations: ^2.0.11
  auto_route: ^8.2.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  cronet_http: ^1.3.1
  cupertino_http: ^1.5.0
  cupertino_icons: ^1.0.8
  responsive_framework: ^1.4.0
  
  eva_icons_flutter: ^3.1.0
  expandable_bottom_sheet: ^1.1.1
  expandable_widgets: ^1.0.3
  fetch_client: ^1.1.2
  flutter_custom_clippers: ^2.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  avatar_glow: ^2.0.2
  flutter_adaptive_scaffold: ^0.1.11
  flutter_animate: ^4.5.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: ^2.5.1
  
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10
  formz: ^0.7.0
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.7.0
  http: ^1.2.1
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^4.0.0
  
  intl: ^0.19.0
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.0
  loading_animation_widget: ^1.2.1
  
  
  map_launcher: ^3.3.1
  
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  progress_state_button: ^1.0.4
  rich_readmore: ^1.1.1
  riverpod_annotation: ^2.3.5
  cuberto_bottom_bar: ^3.1.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sliver_app_bar_builder: ^1.1.0
  smooth_sheets: ^0.7.3
  social_auth_buttons: ^2.0.2
  speech_to_text: ^6.6.0
  talker_flutter: ^4.2.4
  talker_riverpod_logger: ^1.0.4
  url_launcher: ^6.3.0
  visibility_detector: ^0.4.0+2
  uuid: ^4.4.0
  very_good_infinite_list: ^0.7.1
  wave: ^0.2.2
  custom_rating_bar: ^3.0.0
  
  
  
dev_dependencies:
  analyzer: 6.4.1
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  package_rename: ^1.7.0
  riverpod_generator: ^2.4.0
dependency_overrides:
  riverpod:
      git:
        url: https://github.com/rrousselGit/riverpod.git
        path: packages/riverpod
        ref: 28d70d0 # dev
  flutter_riverpod:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/flutter_riverpod
      ref: 28d70d0 # dev
  riverpod_annotation:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_annotation
      ref: 28d70d0 # dev
  riverpod_generator:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_generator
      ref: 28d70d0 # dev
  riverpod_analyzer_utils:
    git:
      url: https://github.com/rrousselGit/riverpod.git
      path: packages/riverpod_analyzer_utils
      ref: 28d70d0 # dev

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/logo.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

package_rename_config:
  android:
    app_name: FindAll # (String) The display name of the android app
    package_name: com.findall.findall.fin_dall # (String) The product bundle identifier of the android app
    override_old_package: com.findall.FindAll # (Optional) (String) The old package name of the android app

  ios:
    app_name: FindAll # (String) The display name of the ios app
    bundle_name: com.findall.findall.fin_dall # (String) The bundle identifier of the ios app
    package_name: com.com.findall.findall.fin_dall # (String) The product bundle identifier of the ios app

flutter:
  uses-material-design: true
  assets:
    - assets/img/
