
/*
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGDMyy4jJjVkNTi5ruqnHjs9ikCYTlMsQ',
    appId: '1:990064363330:android:286702eec0eba56993eadb',
    messagingSenderId: '990064363330',
    projectId: 'fin-dall-7c84d',
    storageBucket: 'fin-dall-7c84d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOUgUGk7KSFipb9A-dH0Y1xopjenhCICY',
    appId: '1:990064363330:ios:cfdc2155270d3b5a93eadb',
    messagingSenderId: '990064363330',
    projectId: 'fin-dall-7c84d',
    storageBucket: 'fin-dall-7c84d.appspot.com',
    androidClientId:
        '990064363330-1g66e65o8bg6vb1plh21fk8lqcmrrbrr.apps.googleusercontent.com',
    iosClientId:
        '990064363330-uik412k5le3sh8495ce8kfsba29j9022.apps.googleusercontent.com',
    iosBundleId: 'com.findall.findall.finDall',
  );
}
*/